hostname: 127.0.0.1 # broker host name
port: 1101  # broker port
log-dir: ~/.shapleq/log # log directory
data-dir: ~/.shapleq/data # data directory
log-level: DEBUG # DEBUG/INFO/WARNING/ERROR
timeout: 10000
zookeeper:
  addresses: localhost:2181
  timeout: 5000